### ISSUE TITLE
Scaffold-DbContext error about missing Create method impementation in netcore 3.0.100-preview6

### ISSUE THREAD

**Issue by mihula** [CrazyJson/Citms.EntityFrameworkCore.Oracle#27]
Hi
when try to use Scaffold-DbContext with Citms.EntityFrameworkCore.Oracle as provider

call
`Scaffold-DbContext -Connection  "<connection_string>" -Provider citms.entityframeworkcore.oracle -OutputDir Models`

Visual Studio 2019 (preview 4) returns error:
**Method 'Create' in type 'Microsoft.EntityFrameworkCore.Oracle.Scaffolding.Internal.OracleDatabaseModelFactory' from assembly 'Citms.EntityFrameworkCore.Oracle, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.**

```
System.TypeLoadException: Method 'Create' in type 'Microsoft.EntityFrameworkCore.Oracle.Scaffolding.Internal.OracleDatabaseModelFactory' from assembly 'Citms.EntityFrameworkCore.Oracle, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.EntityFrameworkCore.Oracle.Design.Internal.OracleDesignTimeServices.ConfigureDesignTimeServices(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices(String provider, IServiceCollection services, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

**Comment by michael712520** [comment]
同样的问题不能使用dbfrist

**Comment by mihula** [comment]
So probably you can close it as won't fix. :(
